### ISSUE TITLE
[BUG] Blank page when errors triggered

### ISSUE THREAD

**Issue by taat** [Ppito/zf3-whoops#11]
Similar issue to this one: https://github.com/Ppito/zf3-whoops/issues/5
but not the same.

## Bug description

When any php error is triggered it's not displayed (blank page).

## Enviroment 

ppito/zf3-whoops                               1.3.1 
zendframework/zend-mvc                         3.1.1  
php 5.6
xdebug
Ubuntu
error_reporting and display_errors properly configured

## Steps to reproduce

Install ZF Skeleton Application (ZF3)
Install the module, copy the sample config to `/config/autoload/`, remove .dist extension

In any controller throw any exception. Whoops page is shown properly.

In any controller trigger any php error (eg. `trigger_error('foo')`), instead of a whoops page or any error information at all - blank page is displayed.

Disable the module (comment module name in modules.config.php) errors - are properly displayed.

So this is definitely caused by this module.

**Comment by taat** [comment]
This was caused by wrong defaults in the sample config file.
(once you copied it to `/config/autoload/` default paths are wrong).

This setting is not needed at all by default, so by default they should be commented.

Is:

```
    'view_manager' => [
        'template_map' => [
           'zf3_whoops/simple_error' => __DIR__ . '/../view/render.phtml',
            'zf3_whoops/twig_error'   => __DIR__ . '/../view/twig/render.html.twig',
        ],
    ],
```

should be:

```
    'view_manager' => [
        'template_map' => [
//            'zf3_whoops/simple_error' => __DIR__ . '/../view/render.phtml',
//            'zf3_whoops/twig_error'   => __DIR__ . '/../view/twig/render.html.twig',
        ],
    ],
```

**Comment by Ppito** [comment]
Hello @taat 

Sorry for your problem, unfortunately your case is wrong.
If you are read carefully the README file, you will see that the copy of configuration is **optional**

> 6. **optional** : copy `config/module.config.php` in `my/project/directory/config/autoload/zf3-whoops.local.php`
> 7. **optional** : edit `my/project/directory/config/autoload/zf3-whoops.local.php`

**If you do not need to change any configuration, don't copy the file.** The step 6 and 7 are only for overload some configuration, for example : activate the features Twig or the Visibility Manager!?

**Comment by taat** [comment]
Sure, module worked without the config of course. 

But the usual practice for zend modules is to have an (optional) config file with .dist extension to drop to `config/autoload/` dir without any changes. This is also a place to document available options.

Anyways, such a 'blank page` errors are hard to debug, so the confusion could be avoided by providing better sample config file.   

BTW, The documentation also states that editing this optional file is also optional

Thank you @Ppito
