### ISSUE TITLE
ZFW-6: Error when working in console mode

### ISSUE THREAD

**Issue by sfurionix** [Ppito/zf3-whoops#12]
Error when working with the zendframework/zend-mvc-console package. 
Version ppito/zf3-whoops: 1.3.1
Perhaps need to add a check if $response is a Zend\Console\Response object, then do nothing.
```
Error: Call to undefined method Zend\Console\Response::getStatusCode() in file www\vendor\ppito\zf3-whoops\src\Module.php on line 151
Stack trace:
  1. Error->() www\vendor\ppito\zf3-whoops\src\Module.php:151
  2. WhoopsErrorHandler\Module->prepareException() www\vendor\zendframework\zend-eventmanager\src\EventManager.php:322
  3. Zend\EventManager\EventManager->triggerListeners() www\vendor\zendframework\zend-eventmanager\src\EventManager.php:171
  4. Zend\EventManager\EventManager->triggerEvent() www\vendor\zendframework\zend-mvc\src\DispatchListener.php:152
  5. Zend\Mvc\DispatchListener->onDispatch() www\vendor\zendframework\zend-eventmanager\src\EventManager.php:322
  6. Zend\EventManager\EventManager->triggerListeners() www\vendor\zendframework\zend-eventmanager\src\EventManager.php:179
  7. Zend\EventManager\EventManager->triggerEventUntil() www\vendor\zendframework\zend-mvc\src\Application.php:332
  8. Zend\Mvc\Application->run() www\public\index.php:40
```

**Comment by Ppito** [comment]
Hello,

Sorry for your problem.
I'll fix it as soon as possible.

However, since 3 months [zend-console](https://github.com/zendframework/zend-console#deprecated) is become deprecated, so perhaps you'll need to change your library !?

**Comment by Ppito** [comment]
I merged a fix in development branch, can you test it and tell me if everything is good ?

**Comment by sfurionix** [comment]
Hello, Mickael.
Thank you for responding.
I checked development branch. Everything works well.
I use zend-console for [slm/queue](https://github.com/JouwWeb/SlmQueue) package. It works only with zend-console.

**Comment by Ppito** [comment]
Hi Sfurionix,

I create a new release with the fix.

Have a nice day,
