### ISSUE TITLE
ZFW-4: User visibility management

### ISSUE THREAD

**Issue by Gamewalker** [Ppito/zf3-whoops#4]
Hello,
is this visible for users or configurable to bind to an admin user/cookie etc? Or is this mod only for dev environments?

**Comment by Ppito** [comment]
Hello Gamewalker,

Sorry for the reply delay.
If you use the development environment of ZendFramework 3 (zf-development-mode enable), you can add the module in development.config.php instead of modules.config.php.
Otherwise, you need to remove the loaded module of your production environment.

**Comment by Ppito** [comment]
Hello,

After thinking, this can be a good idea and I have an idea of the implementation. ;)

**Comment by Ppito** [comment]
Hello Gamewalker,

You can find the new improvement in branch ZFW-4, can you make me a feedback on it, please ?  
Look the README for see the usage guide.

Have fun ;)

**Comment by Gamewalker** [comment]
looks nice, I will test it soon :)

**Comment by Ppito** [comment]
Hello Gamewalker,

You don't tell me if is ok for you ?
