### ISSUE TITLE
Clicking on stack filenames doesn't change editor

### ISSUE THREAD

**Issue by bitwombat** [Ppito/zf3-whoops#6]
I think the source editor may be broken - I see no syntax highlighting, highlighted lines or line numbers (unlike the screenshots for Whoops).

Also, if I click on the filenames in the left column, the source view goes away completely (right column starts with "Environment & details".

Screenshots attached.

![selection_052](https://cloud.githubusercontent.com/assets/3937658/25319456/b219303e-28e1-11e7-9b55-ae86575424a8.png)
![selection_053](https://cloud.githubusercontent.com/assets/3937658/25319455/b2087ab4-28e1-11e7-8654-63f898eaebea.png)

**Comment by Ppito** [comment]
Hello @bitwombat ,

I tried to understand your new bug, and I found your problem...
I reproduced your problem by commenting this line : 
```php
$this->service->writeToOutput(false);
```
... yes it's the result of your other issue, I started to looking for a workaround of this.

**Comment by bitwombat** [comment]
Sorry Ppito, I should have mentioned that :(
Interestingly, with a PHP syntax error, the whole interface works.  This problem just seems to happen when there's a PHP exception.

Anyway, we'll focus on the other issue and see what happens with this.
